services:
  api:
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
          ignore:
            - api/.venv/
            - api/laws/data/
        - action: rebuild
          path: ./api./uv.lock

  redis:
    ports:
      - "6379:6379"

  mongo:
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false