volumes:
  db_data:
  redis_data:

services:
  web:
    # Build the image from the Dockerfile in the current directory
    build: ./api

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"

    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ./api
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - api/.venv/
            - api/laws/data/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./api./uv.lock

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  redis:
    image: valkey/valkey:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - VALKEY_EXTRA_FLAGS='--save 60 1 --loglevel warning'
    volumes:
      - redis_data:/data
