volumes:
  db_data:
  redis_data:

services:
  web:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - API_URL=http://localhost:8000

  api:
    build: ./api
    ports:
      - "8000:80"
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/
      - REDIS_URL=redis://redis:6379

  worker:
    build: ./api
    command: rq worker --url redis://redis:6379 --with-scheduler
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - db_data:/data/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: valkey/valkey:latest
    restart: always
    volumes:
      - redis_data:/data
    environment:
      - VALKEY_EXTRA_FLAGS=--save 60 1 --loglevel warning